name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main  # ou a branch que você usa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Supabase CLI
        run: npm install -g supabase

      - name: Deploy função
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref jkfgxpaiajngdgiubdfu
          supabase functions deploy minha-funcao
