// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkfgxpaiajngdgiubdfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZmd4cGFpYWpuZ2RnaXViZGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTg3NzQsImV4cCI6MjA2MTc5NDc3NH0.Q081NhbSqxf72YsHZTlW-XGSbrzmKI0Kh5lkpEx8618";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);